#!/bin/sh

### BEGIN INIT INFO
# Provides:		adlinkstartup
# Required-Start:	$local_fs $remote_fs $network
# Required-Stop:	$local_fs $remote_fs $network
# Should-Start:
# Should-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	starts adlinkstartup
# Description:		adlinkstartup implements Adlink startup script
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/adlinkstartup
NAME=adlinkstartup
DESC="System daemon implementing the Adlink startup script"
USER="root"


#Changing Permission of SEMA
chmod a+x /usr/bin/semautil


if [ -x /usr/bin/semautil ]; then
	modprobe i2c_i801
	modprobe adl-bmc
	modprobe adl-bmc-boardinfo
	modprobe adl-bmc-vm
	modprobe adl-bmc-wdt
	modprobe adl-bmc-hwmon
	modprobe adl-bmc-nvmem
	modprobe adl-bmc-bklight
	modprobe gpio-pca953x
fi


if [ -x /usr/bin/startxfce4 ]; then
     #removing unwanted applications
   rm /usr/share/applications/exo-mail-reader.desktop
   rm /usr/share/applications/xinput_calibrator.desktop
fi 

#Running docker daemon
if [ -x /usr/bin/dockerd ]; then
    dockerd &
fi

#Running tpm daemon
if [ -x /usr/sbin/tpm2-abrmd ]; then
   sleep 2 
   . /etc/init.d/tpm2-abrmd start & 	
fi
