#!/bin/bash

amixer -c0 cset name='Headphone Jack Switch' 'Off'
amixer -c0 cset name='Headphone Jack Switch' 'On'

amixer -c0 cset name='Mic Jack Switch' 'Off'
amixer -c0 cset name='Mic Jack Switch' 'On'

amixer -c0 cset name='Left Line Mixer Line2R Bypass Volume' '0' 
amixer -c0 cset name='Right Line Mixer Line2L Bypass Volume' '0'
amixer -c0 cset name='Left HP Mixer Line2R Bypass Volume' '0'
amixer -c0 cset name='Right HP Mixer Line2L Bypass Volume' '0'
amixer -c0 cset name='Left HPCOM Mixer Line2R Bypass Volume' '0'
amixer -c0 cset name='Right HPCOM Mixer Line2L Bypass Volume' '0'
amixer -c0 cset name='Line Line2 Bypass Volume' '0'
amixer -c0 cset name='HP Line2 Bypass Volume' '0'
amixer -c0 cset name='HPCOM Line2 Bypass Volume' '0'
amixer -c0 cset name='Class-D Playback Volume' '0'
amixer -c0 cset name='PCM Playback Volume' '127'
amixer -c0 cset name='Left Line Mixer PGAR Bypass Volume' '0'
amixer -c0 cset name='Left Line Mixer DACR1 Playback Volume' '118'
amixer -c0 cset name='Right Line Mixer PGAL Bypass Volume' '0'
amixer -c0 cset name='Right Line Mixer DACL1 Playback Volume' '0'
amixer -c0 cset name='Left HP Mixer PGAR Bypass Volume' '0'
amixer -c0 cset name='Left HP Mixer DACR1 Playback Volume' '0'
amixer -c0 cset name='Right HP Mixer PGAL Bypass Volume' '0'
amixer -c0 cset name='Right HP Mixer DACL1 Playback Volume' '0'
amixer -c0 cset name='Left HPCOM Mixer PGAR Bypass Volume' '0'

amixer -c0 cset name='Left HPCOM Mixer DACR1 Playback Volume' '0'
amixer -c0 cset name='Right HPCOM Mixer PGAL Bypass Volume' '0'
amixer -c0 cset name='Right HPCOM Mixer DACL1 Playback Volume'
amixer -c0 cset name='Line PGA Bypass Volume' '0'
amixer -c0 cset name='Line DAC Playback Volume' '118'
amixer -c0 cset name='HP PGA Bypass Volume' '0'
amixer -c0 cset name='HP DAC Playback Volume' '118'
amixer -c0 cset name='HPCOM PGA Bypass Volume' '0'
amixer -c0 cset name='HPCOM DAC Playback Volume' '0'
amixer -c0 cset name='Line Playback Switch' 'On'
amixer -c0 cset name='HP Playback Switch' 'On'
amixer -c0 cset name='HPCOM Playback Switch' '0ff'
amixer -c0 cset name='AGC Switch' 'Off'
amixer -c0 cset name='Left AGC Target level' '0'
amixer -c0 cset name='Right AGC Target level' '0'
amixer -c0 cset name='Left AGC Attack time' '0'
amixer -c0 cset name='Right AGC Attack time' '0'
amixer -c0 cset name='Left AGC Decay time' '0'
amixer -c0 cset name='Right AGC Decay time' '0'
amixer -c0 cset name='De-emphasis Switch' 'Off'

amixer -c0 cset name='PGA Capture Volume' '0'
amixer -c0 cset name='PGA Capture Switch' 'On'
amixer -c0 cset name='ADC HPF Cut-off' '0'
amixer -c0 cset name='Output Driver Power-On time' '0'
amixer -c0 cset name='Output Driver Ramp-up step' '0'
amixer -c0 cset name='Right HPCOM Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Right HPCOM Mixer DACL1 Switch' 'Off'
amixer -c0 cset name='Right HPCOM Mixer PGAR Bypass Switch' 'Off'
amixer -c0 cset name='Right HPCOM Mixer DACR1 Switch' 'Off'
amixer -c0 cset name='Right HPCOM Mixer Line2L Bypass Switch' 'Off'
amixer -c0 cset name='Right HPCOM Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer DACL1 Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer PGAR Bypass Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer DACR1 Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer Line2L Bypass Switch' 'Off'
amixer -c0 cset name='Left HPCOM Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Right HP Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Right HP Mixer DACL1 Switch' 'Off'
amixer -c0 cset name='Right HP Mixer PGAR Bypass Switch' 'Off'

amixer -c0 cset name='Right HP Mixer DACR1 Switch' 'On'
amixer -c0 cset name='Right HP Mixer Line2L Bypass Switch' 'Off'
amixer -c0 cset name='Right HP Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Left HP Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Left HP Mixer DACL1 Switch' 'On'
amixer -c0 cset name='Left HP Mixer PGAR Bypass Switch' 'Off'
amixer -c0 cset name='Left HP Mixer DACR1 Switch' 'Off'
amixer -c0 cset name='Left HP Mixer Line2L Bypass Switch' 'Off'
amixer -c0 cset name='Left HP Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Right Line Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Right Line Mixer DACL1 Switch' 'Off'
amixer -c0 cset name='Right Line Mixer PGAR Bypass Switch' 'Off'
amixer -c0 cset name='Right Line Mixer DACR1 Switch' 'On'
amixer -c0 cset name='Right Line Mixer Line2L Bypass Switch' 'Off'
amixer -c0 cset name='Right Line Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Left Line Mixer PGAL Bypass Switch' 'Off'
amixer -c0 cset name='Left Line Mixer DACL1 Switch' 'On'
amixer -c0 cset name='Left Line Mixer PGAR Bypass Switch' 'Off'
amixer -c0 cset name='Left Line Mixer DACR1 Switch' 'On'
amixer -c0 cset name='Left Line Mixer Line2L Bypass Switch' 'Off'

amixer -c0 cset name='Left Line Mixer Line2R Bypass Switch' 'Off'
amixer -c0 cset name='Right Line2R Mux' '0'
amixer -c0 cset name='Right PGA Mixer Line1R Switch' 'On'
amixer -c0 cset name='Right PGA Mixer Line1L Switch' 'Off'
amixer -c0 cset name='Right PGA Mixer Line2R Switch' 'Off'
amixer -c0 cset name='Right PGA Mixer Mic3L Switch' 'Off'
amixer -c0 cset name='Right PGA Mixer Mic3R Switch' 'On'
amixer -c0 cset name='Left Line2L Mux' '0'
amixer -c0 cset name='Left PGA Mixer Line1L Switch' 'On'
amixer -c0 cset name='Left PGA Mixer Line1R Switch' 'Off'
amixer -c0 cset name='Left PGA Mixer Line2L Switch' 'Off'
amixer -c0 cset name='Left PGA Mixer Mic3L Switch' 'On'
amixer -c0 cset name='Left PGA Mixer Mic3R Switch' 'Off'
amixer -c0 cset name='Right Line1R Mux' '0'
amixer -c0 cset name='Right Line1L Mux' '0' 
amixer -c0 cset name='Left Line1R Mux' '0'
amixer -c0 cset name='Left Line1L Mux' '0'
amixer -c0 cset name='Right HPCOM Mux' '0'
amixer -c0 cset name='Right DAC Mux' '0'
amixer -c0 cset name='Left HPCOM Mux' '0'
amixer -c0 cset name='Left DAC Mux' '0'

echo "Done!!"

